name: TCPShield
version: 2.7.0
main: net.tcpshield.tcpshield.bukkit.TCPShieldBukkit
softdepend:
- ProtocolLib
- floodgate
author: https://tcpshield.com
description: TCPShield IP parsing capabilities for Velocity
api-version: 1.16
